### ISSUE TITLE
Could you provide some executables of this project?

### ISSUE THREAD

**Issue by i30817** [unknownbrackets/maxcso#1]
I'm on linux only and have no way to build the stuff, i'd like it to run it over my collection on wine.

**Comment by unknownbrackets** [comment]
It's under Releases:
https://github.com/unknownbrackets/maxcso/releases/tag/v1.4.4

The release 7z contains a Windows 64-bit maxcso.exe and a 32-bit maxcso32.exe.

Most likely this would build on Linux easily by stubbing out the 7-zip compression method, or else maybe applying some of the stuff p7zip does.  But yes, I expect it to work fine with wine.

-[Unknown]

**Comment by i30817** [comment]
Mmm, i think i'll wait to compress things until PPSSPP has zso support at least, i don't want to do it twice for every iso, because it's quite slow.

**Comment by unknownbrackets** [comment]
Well, ZSO is generally worse compression.  On any modern mobile or desktop device, the change in decompression speed won't be significant (actually reading blocks together rather than one-at-a-time was much more significant on even PSPs, iirc.)

CSOv2 (mixed lz4 and zlib) can provide better compression and slightly better decompression speed, but it's not significant and probably won't gain support in CFW.

If you want something that will work both with CFW and PPSSPP, you're pretty much stuck with either ZSO (which will have worse compression, and isn't yet supported by PPSSPP) or CSO with the default block size (which won't really have significantly different compression.)

If you don't care about CFW, I would just go for `--block=16384` or so with CSO, which should be a little smaller and will not really have any performance problems reading.

-[Unknown]

**Comment by i30817** [comment]
My pc isn't exactly modern ;), i believe decompression speed is more important to me.

**Comment by unknownbrackets** [comment]
Well, there's two different things here:
 * Decompression speed
 * Compression ratio

It's important to separate these.  lz4 has higher decompression *speed*, probably between 5-10 times faster.  It does this with a *worse* compression ratio.

So for example, some theoretical (but realistic) sizes:
 * ISO: 1000 MB
 * CSO: 580 MB
 * ZSO: 660 MB

Now, again, it decompresses faster.  It has to read more data from the disk so it would take profiling to see where the trade-off is, but most likely lz4 would win on **speed**.  But it will generate a larger file.

As far as size (disk space), obviously CSO is superior (and a larger block size will be better in both cases.)

CSOv2 basically retains the size of CSOv1, while mixing in some amount of lz4 for improved speed (so e.g. it would be 25% lz4 and 75% zlib.)  CSOv2 can even get better compression ratios than CSOv1 (with only say 5% lz4.)

Larger block sizes will also have an effect on decompression time, but it's more involved (this applies to all formats):
 * Random access will be slower, because it has to decompress more for each access.
 * Sequential access (which is common) is likely to be slightly faster.
 * Compression ratio will improve.
 * Memory usage will increase (get worse.)

So, it's got more trade-offs.  In most cases, I think it's a win to increase block size but it can vary.

As for PPSSPP - might get lz4 but probably needs some motivation.  As it is, it seems like CSOv2 and ZSO are both doomed to obscurity, really.

-[Unknown]

**Comment by i30817** [comment]
I see, cso1 with large block size it is then.
