### ISSUE TITLE
[request] Dax as output format

### ISSUE THREAD

**Issue by Danixu** [unknownbrackets/maxcso#15]
Hello,

Recently I've bought a PSP console because mine was damaged long time ago, and I've noticed that the latest M33 firmware is compatible with DAX format (that saves some space), so would be nice to have this format as output format too.
I've seen that you've added LZ4 format as output (PRO firmware compatible), but the size is the same as CSO (of course, will be faster on some games).

Thanks!!

**Comment by unknownbrackets** [comment]
If I remember right, DAX is basically CSO with more overhead (more header data), but larger default block size.  In that case, you can beat DAX with maxcso using the `--block=8192` option.

Some CSO implementations only support the default block size (2048) - does M33?  I believe PRO doesn't, because they couldn't spare extra RAM (which is probably why they don't support DAX either?)

DAX is probably not hard to add support for, but if CSO would work better it might make more sense to just use that.

ZSO should almost always be a bit larger than a CSO, but may indeed load faster on the PSP's CPU (only because it's 222Mhz - 333Mhz.)

-[Unknown]

**Comment by Danixu** [comment]
You're rigth. Thanks for the info...

8192 as block size compress even a bit more than dax, but looks like M33 is not compatible (it don't shows the game on VHS). Maybe will be nice for PC emulators.

I've tested 4096 block size too, but don't works.

Greetings!!

**Comment by unknownbrackets** [comment]
Will be implemented in #16.  Will make a release later.

-[Unknown]

**Comment by Danixu** [comment]
Thank you very much!!!

**Comment by unknownbrackets** [comment]
Released in v1.10.0.  Use --format=dax like so:

maxcso --format=dax somefile.iso

Other options like --fast and --use-zopfli still work.  It can also go directly from a .cso to a .dax file.

-[Unknown]
