### ISSUE TITLE
Can the program to compress from STDIN?

### ISSUE THREAD

**Issue by reinaldorauch** [unknownbrackets/maxcso#19]
I want to write a script that extracts a 7z file with an iso file inside and compress it to cso without writing the iso file to disk. The method that I thought was piping the output of 7zip program to stdin of maxcso to compress and write the cso file. It can be done?

**Comment by unknownbrackets** [comment]
Hmm, this is probably possible but would require a number of changes.

Right now reading is fairly deliberate and uses libuv - we start by detecting the file type from the first 24 bytes:
https://github.com/unknownbrackets/maxcso/blob/bb81691c8a55f774f024031bf777f1523d439a40/src/input.cpp#L49

We then need the [total ISO size](https://github.com/unknownbrackets/maxcso/blob/bb81691c8a55f774f024031bf777f1523d439a40/src/input.cpp#L157) to be able to plan the threading and index size properly for async write IO.  It'd need to buffer the next 16 sectors, look at the volume descriptor, and then release the initial sectors and volume descriptor to the compressor to thread and write.

The next problem is that we'd have to use `uv_read_start` instead of `uv_fs_read`, and that reads an indeterminate number of bytes each call.  So we'd need to do a lot of constant buffering and copying to get them in proper, compressible sectors.

There's even more to deal with for DAX and CSO via stdin, so it's tempting to just have a dedicated (and completely separate) code path for stdin.  One that will probably receive poor testing in future versions...

So - unfortunately - it would require quite a few changes.  I would accept a pull request (assuming it still worked with files and wasn't drastically slower), but it's a more significant change than I presently have time and interest to make myself.

-[Unknown]

**Comment by reinaldorauch** [comment]
Thanks for the reply @unknownbrackets .

I understood the needed changes and I agreed that would be a little of a hassle to make it. This not worth the cost of doing it as it would be just for convenience. 

Thanks again for the time in answering. I will close the issue as it is resolved.
