### ISSUE TITLE
Can't handle files

### ISSUE THREAD

**Issue by faroukabd000** [unknownbrackets/maxcso#36]
I have downloaded a compressed  rom but the file format was  .bin + .cue
The converter can't do the compression
Why?

**Comment by unknownbrackets** [comment]
This is basically the same as #13.  `maxcso` doesn't support MODE2 discs (i.e. many PS1 games, and a few uncommon PS2 games.)

Just for clarity, MODE2 is only a CD thing.  DVDs, UMDs, blu-rays, etc. always have error correction data and are essentially always "MODE1".  But most PS1 games decided to throw away the CD-ROM scratch-protection in exchange for 13% more bytes of space on each CD.  That's why they were so easy to scratch and break your game.

All implementations of CSO I'm aware of similarly don't support MODE2, so even if you were able to compress a MODE2 disc, you wouldn't be able to use it anywhere until you decompressed it.  In that case, it's probably better to use `xz`.

That said, I've left #13 open because I might make it work or accept a pull request implementing it.  Closing this in favor of that.

-[Unknown]
