### ISSUE TITLE
Can't pipe stderr

### ISSUE THREAD

**Issue by alucryd** [unknownbrackets/maxcso#37]
Hi, I'm in a similar boat as https://github.com/unknownbrackets/maxcso/issues/19, I am invoking maxcso from a rust application and would like to monitor the progress via a progress bar.

Trying to pipe to stdin prints `Error while processing /dev/stdin: Not able to read first 24 bytes`.

Another solution would be to pipe stderr and parse the progress lines from maxcso, however it seems stderr is completely bypassed when piping, which is very unfortunate.

**Comment by unknownbrackets** [comment]
I'd really recommend calling it via API rather than piping, if that's an option.  In other words, calling this:
https://github.com/unknownbrackets/maxcso/blob/49665c1779bdd96283898b790b636b8f06539461/src/compress.h#L56-L67

I think Rust FFI doesn't support C++, so this might require a little `extern "C"` wrapper, but then rather than trying to parse all the ANSI that libuv will output, you could just get `int64_t pos, int64_t total, int64_t written` directly and calculate progress any way you like.

That said, if you really want to do this, you'd need to give maxcso a tty.  It intentionally does not write formatting and progress when not a tty:
https://github.com/unknownbrackets/maxcso/blob/49665c1779bdd96283898b790b636b8f06539461/cli/cli.cpp#L408

This is in other words basically `isatty()`.  I haven't tried it, but I assume you could use a pty.

Piping a file in via stdin is a trickier problem.  `maxcso` requires seeking, especially for CSO/DAX/etc. inputs, and uses async IO on multiple threads to read different parts of the file concurrently (this is a major part of its design.)

Overall, it's not built in a way that's friendly to streaming data in.  It would impact threading efficiency to force it to read bytes synchronously from the stream, one sector at a time.  Even if that was changed, the output file really has to generate using seeking, unless the entire file is buffered in RAM before writing anything (currently it uses async IO to write the file too.)

Essentially, it always uses `preadv()`/`pwritev()`.  I assume it's getting ESPIPE and that's why it's unable to read even the first 24 bytes.

-[Unknown]

**Comment by alucryd** [comment]
Thank you very much for the valuable information! I knew piping to stdin was out of the question so I fell back to monitoring what goes out.

I will try to give the process a pty first, and once I'm more confident in rust I will give the task API a try. Thanks again!
