### ISSUE TITLE
Unstable speed

### ISSUE THREAD

**Issue by faroukabd000** [unknownbrackets/maxcso#39]
Hi dev
The software have unstable compression speed
I used  onimusha3  the start speed was 5.6mb/s
And ratio 2%  until 70% of the process the speed dropped to 0.9mb/s  ( i didn't use anything 
That  consume ram or cpu )
For the most other games the speed always dropped so much

**Comment by unknownbrackets** [comment]
Unless you use `--fast`, `maxcso` is going to try to compress the same data in the file multiple times on multiple threads to get the smallest possible file.  It uses different compression algorithms, and this is considered "brute force" compression.

Compression, in general, is not a constant speed operation.  Easy to compress data will compress faster than hard to compress data.

Because `maxcso` does his brute forcing, it multiplies this effect.  It's actually attempting to compress the file 5 times, by default.  So even the normal little differences get multiplied significantly.

On an Intel i7-8700, I get about 12 MB/s average, but when using my hard disk it drops down every second because the disk requires time.  Using `--fast` I get closer to 80 MB/s average, because it only uses the equivalent of `gzip -9`.

Do you get the same performance drop even with `--fast`?

-[Unknown]

**Comment by faroukabd000** [comment]
––fast?
I don't know how to use cmd😂

**Comment by unknownbrackets** [comment]
This is the first result I found on Google for "how to use cmd basic tutorial":
https://www.youtube.com/watch?v=8JzW1l4wfmQ

-[Unknown]

**Comment by unknownbrackets** [comment]
Closing this based on the above - I think this is expected.

-[Unknown]
