### ISSUE TITLE
Add a table to the ReadMe documenting to which software and firmware which version of the format and compression is compatible

### ISSUE THREAD

**Issue by KOLANICH** [unknownbrackets/maxcso#48]

**Comment by unknownbrackets** [comment]
maxcso mainly supports other formats than CSO1 to be able to convert them to CSO1.  There's a reason why CSO2 is marked as experimental: to convey exactly this information.  It's not supported pretty much anywhere.

As noted in #49, ZSO and CSO2 were experiments that ended up not solving a problem that needed to be solved.  Instead, it was a bug in CFW that still affected ZSO/CSO2 files until it was fixed.

If you're still somehow curious about what software supports what, and you're volunteering to gather it, validate it, and maintain it over time - then please open a pull request.  I may accept it.

Otherwise, I'm very unlikely to spend time gathering and maintaining such information myself, and have seen no interest from another contributor to do so (and I don't expect "No description provided." to motivate anyone to satisfy this passing curiosity.)  That said, I may at some point simply include a list of software that support CSO1, as that's what has widespread support and is actually interesting.

-[Unknown]
